//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt_V2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SklepEntities : DbContext
    {
        public SklepEntities()
            : base("name=SklepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<Egzemplarz> Egzemplarz { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<Zdjecia> Zdjecia { get; set; }
    
        public virtual int AddPracownik(string login, string haslo, string imie, string nazwisko, string uprawnienia, string tel_1, string tel_2, string fax, string email, string wWW, string kraj, string region, string miasto, string kodPocztowy)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("Haslo", haslo) :
                new ObjectParameter("Haslo", typeof(string));
    
            var imieParameter = imie != null ?
                new ObjectParameter("Imie", imie) :
                new ObjectParameter("Imie", typeof(string));
    
            var nazwiskoParameter = nazwisko != null ?
                new ObjectParameter("Nazwisko", nazwisko) :
                new ObjectParameter("Nazwisko", typeof(string));
    
            var uprawnieniaParameter = uprawnienia != null ?
                new ObjectParameter("Uprawnienia", uprawnienia) :
                new ObjectParameter("Uprawnienia", typeof(string));
    
            var tel_1Parameter = tel_1 != null ?
                new ObjectParameter("Tel_1", tel_1) :
                new ObjectParameter("Tel_1", typeof(string));
    
            var tel_2Parameter = tel_2 != null ?
                new ObjectParameter("Tel_2", tel_2) :
                new ObjectParameter("Tel_2", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var wWWParameter = wWW != null ?
                new ObjectParameter("WWW", wWW) :
                new ObjectParameter("WWW", typeof(string));
    
            var krajParameter = kraj != null ?
                new ObjectParameter("Kraj", kraj) :
                new ObjectParameter("Kraj", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var miastoParameter = miasto != null ?
                new ObjectParameter("Miasto", miasto) :
                new ObjectParameter("Miasto", typeof(string));
    
            var kodPocztowyParameter = kodPocztowy != null ?
                new ObjectParameter("KodPocztowy", kodPocztowy) :
                new ObjectParameter("KodPocztowy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPracownik", loginParameter, hasloParameter, imieParameter, nazwiskoParameter, uprawnieniaParameter, tel_1Parameter, tel_2Parameter, faxParameter, emailParameter, wWWParameter, krajParameter, regionParameter, miastoParameter, kodPocztowyParameter);
        }
    
        public virtual int DeletePracownik(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePracownik", idParameter);
        }
    
        public virtual int ModifyPracownik(Nullable<int> id, string login, string haslo, string imie, string nazwisko, string uprawnienia, string tel_1, string tel_2, string fax, string email, string wWW, string kraj, string region, string miasto, string kodPocztowy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("Haslo", haslo) :
                new ObjectParameter("Haslo", typeof(string));
    
            var imieParameter = imie != null ?
                new ObjectParameter("Imie", imie) :
                new ObjectParameter("Imie", typeof(string));
    
            var nazwiskoParameter = nazwisko != null ?
                new ObjectParameter("Nazwisko", nazwisko) :
                new ObjectParameter("Nazwisko", typeof(string));
    
            var uprawnieniaParameter = uprawnienia != null ?
                new ObjectParameter("Uprawnienia", uprawnienia) :
                new ObjectParameter("Uprawnienia", typeof(string));
    
            var tel_1Parameter = tel_1 != null ?
                new ObjectParameter("Tel_1", tel_1) :
                new ObjectParameter("Tel_1", typeof(string));
    
            var tel_2Parameter = tel_2 != null ?
                new ObjectParameter("Tel_2", tel_2) :
                new ObjectParameter("Tel_2", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var wWWParameter = wWW != null ?
                new ObjectParameter("WWW", wWW) :
                new ObjectParameter("WWW", typeof(string));
    
            var krajParameter = kraj != null ?
                new ObjectParameter("Kraj", kraj) :
                new ObjectParameter("Kraj", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var miastoParameter = miasto != null ?
                new ObjectParameter("Miasto", miasto) :
                new ObjectParameter("Miasto", typeof(string));
    
            var kodPocztowyParameter = kodPocztowy != null ?
                new ObjectParameter("KodPocztowy", kodPocztowy) :
                new ObjectParameter("KodPocztowy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifyPracownik", idParameter, loginParameter, hasloParameter, imieParameter, nazwiskoParameter, uprawnieniaParameter, tel_1Parameter, tel_2Parameter, faxParameter, emailParameter, wWWParameter, krajParameter, regionParameter, miastoParameter, kodPocztowyParameter);
        }
    
        public virtual int Pracownicy_Insert(string login, string haslo, string imie, string nazwisko, string uprawnienia, string tel_1, string tel_2, string fax, string email, string wWW, string kraj, string region, string miasto, string kodPocztowy)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("Haslo", haslo) :
                new ObjectParameter("Haslo", typeof(string));
    
            var imieParameter = imie != null ?
                new ObjectParameter("Imie", imie) :
                new ObjectParameter("Imie", typeof(string));
    
            var nazwiskoParameter = nazwisko != null ?
                new ObjectParameter("Nazwisko", nazwisko) :
                new ObjectParameter("Nazwisko", typeof(string));
    
            var uprawnieniaParameter = uprawnienia != null ?
                new ObjectParameter("Uprawnienia", uprawnienia) :
                new ObjectParameter("Uprawnienia", typeof(string));
    
            var tel_1Parameter = tel_1 != null ?
                new ObjectParameter("Tel_1", tel_1) :
                new ObjectParameter("Tel_1", typeof(string));
    
            var tel_2Parameter = tel_2 != null ?
                new ObjectParameter("Tel_2", tel_2) :
                new ObjectParameter("Tel_2", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var wWWParameter = wWW != null ?
                new ObjectParameter("WWW", wWW) :
                new ObjectParameter("WWW", typeof(string));
    
            var krajParameter = kraj != null ?
                new ObjectParameter("Kraj", kraj) :
                new ObjectParameter("Kraj", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var miastoParameter = miasto != null ?
                new ObjectParameter("Miasto", miasto) :
                new ObjectParameter("Miasto", typeof(string));
    
            var kodPocztowyParameter = kodPocztowy != null ?
                new ObjectParameter("KodPocztowy", kodPocztowy) :
                new ObjectParameter("KodPocztowy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pracownicy_Insert", loginParameter, hasloParameter, imieParameter, nazwiskoParameter, uprawnieniaParameter, tel_1Parameter, tel_2Parameter, faxParameter, emailParameter, wWWParameter, krajParameter, regionParameter, miastoParameter, kodPocztowyParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
