//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkty()
        {
            this.Egzemplarz = new HashSet<Egzemplarz>();
            this.SzczegolyZamowienia = new HashSet<SzczegolyZamowienia>();
            this.Zdjecia = new HashSet<Zdjecia>();
        }
    
        public int ProduktId { get; set; }
        public int KategoriaId { get; set; }
        public int DostawcaId { get; set; }
        public string NazwaProduktu { get; set; }
        public int IloscNaJednostke { get; set; }
        public decimal CenaJednostkowa { get; set; }
        public int LiczbaProduktow { get; set; }
        public string Opis { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egzemplarz> Egzemplarz { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdjecia> Zdjecia { get; set; }
    }
}
