//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzczegolyZamowieniaView
    {
        public string NazwaProduktu { get; set; }
        public decimal CenaJednostkowa { get; set; }
        public decimal Cena { get; set; }
        public int Ilosc { get; set; }
        public float Rabat { get; set; }
        public int IloscNaJednostke { get; set; }
        public string Opis { get; set; }
        public Nullable<int> ZamowienieId { get; set; }
    }
}
